name: install python packages and run python script

on:
  push:
    branches:
      - master
  workflow_dispatch: # Manually trigger the workflow

jobs:
  init:
    name: Install Python packages and run Python script
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          check-latest: true
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: |
          python index_fund_selector.py > output.txt
        working-directory: ./scripts
      - uses: actions/upload-artifact@v4
        with:
          name: results
          path: ./scripts/output.txt
